local L0_0, L3_3, L4_4 = L0_0, ".head", L4_4
L0_0 = L0_0(L3_3)
L3_3 = import
L4_4 = "..head"
L3_3 = L3_3(L4_4)
L4_4 = L3_3.et
;({}).name = "AUTO_GEN_battle_env_battle_env_name_14"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_14"
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_14"
;({}).mt1, ({}).banner = {}, "special_weather_chuansongmen"
_FOR_, _FOR_, _FOR_ = pairs({})
for _FORV_8_, _FORV_9_ in _FOR_, _FOR_, _FOR_ do
	_FORV_9_.__index = _FORV_9_
end
;({}).id = 1
;({}).name = "AUTO_GEN_battle_env_battle_env_name_1"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_1"
;({}).add_speed_rate = 18000
;({}).env_arg, ({}).parabola_change_rate = {}, 2
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_1"
;({}).banner = "fightroom_img_map_magnetic_burst"
;({}).eff_id = 800053
;({}).is_ui_eff = true
L0_0[1], ({}).effect, ({}).add_on_prepare = {}, {}, true
;({}).id = 2
;({}).name = "AUTO_GEN_battle_env_battle_env_name_2"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_2"
;({}).wild_wind_range, ({})[1] = {}, 80
;({}).wild_wind_range, ({})[2] = {}, 100
;({}).normal_wind_range, ({})[1] = {}, 40
;({}).normal_wind_range, ({})[2] = {}, 60
;({}).wild_wind_round = 3
;({}).env_arg, ({}).wild_wind_rate = {}, 2000
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_2"
;({}).banner = "fightroom_img_map_wild_wind"
;({}).eff_id = 800054
;({}).is_ui_eff = true
L0_0[2], ({}).effect, ({}).add_on_prepare = {}, {}, true
;({}).id = 3
;({}).name = "AUTO_GEN_battle_env_battle_env_name_3"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_3"
;({}).env_arg = L4_4
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_3"
;({}).banner = "fightroom_img_map_heavy_fog"
L0_0[3], ({}).effect = {}, L4_4
;({}).id = 4
;({}).name = "AUTO_GEN_battle_env_battle_env_name_4"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_4"
;({}).env_arg = L4_4
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_4"
;({}).banner = "fightroom_img_map_time_bomb"
L0_0[4], ({}).effect = {}, L4_4
;({}).id = 5
;({}).name = "AUTO_GEN_battle_env_battle_env_name_5"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_5"
;({}).env_arg = L4_4
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_5"
;({}).banner = "fightroom_img_map_black_hole"
L0_0[5], ({}).effect = {}, L4_4
;({}).id = 6
;({}).name = "AUTO_GEN_battle_env_battle_env_name_6"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_6"
;({}).env_arg = L4_4
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_6"
;({}).banner = "special_weather_yangguangmingmei"
L0_0[6], ({}).effect = {}, L4_4
;({}).id = 7
;({}).name = "AUTO_GEN_battle_env_battle_env_name_7"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_7"
;({}).env_arg = L4_4
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_7"
;({}).banner = "special_weather_kongtou"
L0_0[7], ({}).effect = {}, L4_4
;({}).id = 8
;({}).name = "AUTO_GEN_battle_env_battle_env_name_8"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_8"
local L10_10 = L10_10
;({}).env_arg, ({}).ps_list, ({})[1] = {}, {}, 393
;({}).env_arg, ({}).ps_list, ({})[2] = {}, {}, 394
;({}).env_arg, ({}).ps_list, ({})[3] = {}, {}, 395
local ({}).env_arg, ({}).ps_list, ({})[4], L11_11 = {}, {}, 396, L11_11
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_8"
;({}).banner = "special_weather_bingxue"
L0_0[8], ({}).effect = {}, L4_4
;({}).id = 9
;({}).name = "AUTO_GEN_battle_env_battle_env_name_4"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_4"
;({}).env_arg = L4_4
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_4"
;({}).banner = "fightroom_img_map_time_bomb"
L0_0[9], ({}).effect = {}, L4_4
;({}).id = 10
;({}).name = "AUTO_GEN_battle_env_battle_env_name_7"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_10"
;({}).env_arg = L4_4
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_7"
;({}).banner = "special_weather_kongtou"
L0_0[10], ({}).effect = {}, L4_4
;({}).id = 11
;({}).name = "AUTO_GEN_battle_env_battle_env_name_11"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_11"
;({}).env_arg = L4_4
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_11"
;({}).banner = "special_weather_leiyu"
;({}).eff_id = 800058
;({}).is_ui_eff = true
L0_0[11], ({}).effect, ({}).add_on_prepare = {}, {}, true
;({}).id = 12
;({}).name = "AUTO_GEN_battle_env_battle_env_name_12"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_12"
;({}).env_arg, ({}).ps_list, ({})[1] = {}, {}, 617
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_12"
;({}).banner = "special_weather_mofafeitan"
L0_0[12], ({}).effect = {}, L4_4
;({}).id = 13
;({}).name = "AUTO_GEN_battle_env_battle_env_name_13"
;({}).desc = "AUTO_GEN_battle_env_battle_env_desc_13"
;({}).env_arg = L4_4
;({}).tip_img = "UI/BigPic/Fight/env/fight_env_13"
;({}).banner = "special_weather_jingxihezi"
L0_0[13], ({}).effect = {}, L4_4
;({}).id = 14
;({}).env_arg = L4_4
;({}).effect = L4_4
L0_0[14] = L10_10({}, L11_11.mt1)
;({}).id = 15
;({}).env_arg = L4_4
;({}).effect = L4_4
local L7_7 = L10_10({}, L11_11.mt1)
L0_0[15] = L7_7
L7_7 = {}
L7_7.id = 16
L7_7.name = "AUTO_GEN_battle_env_battle_env_name_16"
L7_7.desc = "AUTO_GEN_battle_env_battle_env_desc_16"
L7_7.env_arg, ({}).ps_list, ({})[1] = {}, {}, 639
L7_7.tip_img = "UI/BigPic/Fight/env/fight_env_16"
L7_7.banner = "special_weather_cilixie"
L7_7.effect = L4_4
L0_0[16] = L7_7
L7_7 = {}
L7_7.id = 17
L7_7.name = "AUTO_GEN_battle_env_battle_env_name_17"
L7_7.desc = "AUTO_GEN_battle_env_battle_env_desc_17"
local L8_8 = L8_8
;({})[1] = 648
local ({})[2], L9_9 = 651, L9_9
L8_8.ps_list = L9_9
L7_7.env_arg = L8_8
L7_7.tip_img = "UI/BigPic/Fight/env/fight_env_17"
L7_7.banner = "special_weather_yinyuejie"
L7_7.effect = L4_4
L0_0[17] = L7_7
return L0_0
