local L0_0, L3_3, L4_4 = L0_0, ".head", L4_4
L0_0 = L0_0(L3_3)
L3_3 = import
L4_4 = "..head"
L3_3 = L3_3(L4_4)
L4_4 = L3_3.et
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1108"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1108"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 500
;({}).cache_rank = 500
;({}).obj_type = 1
;({}).scope_group_type = 1
;({}).if_show = 1
;({}).mt1, ({}).if_reward = {}, 0
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).cache_rank = 100
;({}).obj_type = 1
;({}).scope_group_type = 1
;({}).if_show = 0
;({}).mt2, ({}).if_reward = {}, 0
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_22"
;({}).like_type = 0
;({}).mt3, ({}).obj_type = {}, 2
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).cache_rank = 500
;({}).mt4, ({}).obj_type = {}, 1
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).cache_rank = 9999
;({}).mt5, ({}).obj_type = {}, 1
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).mt6, ({}).obj_type = {}, 1
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_22"
;({}).refresh_type = 0
;({}).obj_type = 2
;({}).if_show = 0
;({}).mt7, ({}).if_reward = {}, 0
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_22"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 100
;({}).like_type = 0
;({}).mt8, ({}).obj_type = {}, 2
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_22"
;({}).refresh_type = 3
;({}).rank_limit = 30
;({}).cache_rank = 50
;({}).like_type = 0
;({}).mt9, ({}).obj_type = {}, 2
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 200
;({}).cache_rank = 999
;({}).like_type = 12
;({}).obj_type = 1
;({}).mt10, ({}).if_show = {}, 1
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 300
;({}).cache_rank = 600
;({}).mt11, ({}).obj_type = {}, 1
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 99999
;({}).mt12, ({}).obj_type = {}, 1
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 100
;({}).mt13, ({}).obj_type = {}, 1
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 2000
;({}).cache_rank = 2000
;({}).obj_type = 1
;({}).scope_group_type = 1
;({}).if_show = 0
;({}).mt14, ({}).if_reward = {}, 0
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 500
;({}).cache_rank = 500
;({}).obj_type = 1
;({}).scope_group_type = 1
;({}).if_show = 1
;({}).mt15, ({}).if_reward = {}, 0
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 9999
;({}).open_func_id = 302
;({}).mt16, ({}).obj_type = {}, 1
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).mt17, ({}).obj_type = {}, 1
;({}).title = "AUTO_GEN_rank_system_rank_system_title_45"
;({}).refresh_type = 0
;({}).cache_rank = 9999
;({}).if_show = 0
;({}).mt18, ({}).if_reward = {}, 0
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1002"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_22"
;({}).refresh_type = 3
;({}).mt19, ({}).like_type = {}, 0
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1130"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 9999
;({}).hint_show_key = "merge_servers_rank_rule1"
;({}).mt20, ({}).obj_type = {}, 1
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1134"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 9999
;({}).hint_show_key = "merge_servers_rank_rule2"
;({}).mt21, ({}).obj_type = {}, 5
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1140"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 9999
;({}).hint_show_key = "galactic_cycle_rank_personal_rule"
;({}).mt22, ({}).obj_type = {}, 1
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1140"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_1142"
;({}).refresh_type = 0
;({}).rank_limit = 50
;({}).cache_rank = 100
;({}).hint_show_key = "galactic_cycle_rank_server_rule"
;({}).mt23, ({}).obj_type = {}, 6
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1130"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_22"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 9999
;({}).hint_show_key = "merge_servers_rank_rule1"
;({}).obj_type = 2
;({}).if_show = 0
;({}).mt24, ({}).if_reward = {}, 0
;({}).title = "AUTO_GEN_rank_system_rank_system_title_24"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 9999
;({}).like_type = 402
;({}).mt25, ({}).obj_type = {}, 1
;({}).title = "AUTO_GEN_rank_system_rank_system_title_311"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 9999
;({}).like_type = 0
;({}).mt26, ({}).obj_type = {}, 1
;({}).title = "AUTO_GEN_rank_system_rank_system_title_500"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 10
;({}).cache_rank = 10
;({}).like_type = 0
;({}).obj_type = 1
;({}).mt27, ({}).take_snapshot_before_rank = {}, 10
;({}).title = "AUTO_GEN_rank_system_rank_system_title_8"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 300
;({}).cache_rank = 600
;({}).mt28, ({}).obj_type = {}, 1
;({}).title = "AUTO_GEN_rank_system_rank_system_title_14"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 300
;({}).cache_rank = 600
;({}).mt29, ({}).obj_type = {}, 1
;({}).title = "AUTO_GEN_rank_system_rank_system_title_104"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 200
;({}).cache_rank = 200
;({}).mt30, ({}).obj_type = {}, 1
;({}).title = "AUTO_GEN_rank_system_rank_system_title_104"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 200
;({}).cache_rank = 200
;({}).open_func_id = 149
;({}).mt31, ({}).obj_type = {}, 1
_FOR_, _FOR_, _FOR_ = pairs({})
for _FORV_8_, _FORV_9_ in _FOR_, _FOR_, _FOR_ do
	_FORV_9_.__index = _FORV_9_
end
;({}).id = 4
;({}).name = "AUTO_GEN_rank_system_rank_system_name_4"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_4"
;({}).open_func_id = 21
;({}).like_type = 4
;({}).settlement_ids, ({})[1] = {}, 41
L0_0[4] = setmetatable({}, ({}).mt11)
;({}).id = 5
;({}).name = "AUTO_GEN_rank_system_rank_system_name_5"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_5"
;({}).open_func_id = 4701
;({}).like_type = 5
;({}).settlement_ids, ({})[1] = {}, 51
L0_0[5] = setmetatable({}, ({}).mt11)
;({}).id = 6
;({}).name = "AUTO_GEN_rank_system_rank_system_name_6"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_6"
;({}).rank_limit = 9999
;({}).cache_rank = 9999
;({}).open_func_id = 7
;({}).like_type = 6
;({}).settlement_ids, ({})[1] = {}, 6
L0_0[6] = setmetatable({}, ({}).mt6)
;({}).id = 7
;({}).name = "AUTO_GEN_rank_system_rank_system_name_7"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_7"
;({}).open_func_id = 4504
;({}).like_type = 7
;({}).settlement_ids, ({})[1] = {}, 14001
;({}).take_snapshot_before_rank = 10
L0_0[7] = setmetatable({}, ({}).mt11)
;({}).id = 8
;({}).name = "AUTO_GEN_rank_system_rank_system_name_8"
;({}).like_type = 8
;({}).settlement_ids = L4_4
L0_0[8] = setmetatable({}, ({}).mt28)
;({}).id = 9
;({}).name = "AUTO_GEN_rank_system_rank_system_name_9"
;({}).like_type = 9
;({}).settlement_ids, ({})[1] = {}, 91
;({}).take_snapshot_before_rank = 10
L0_0[9] = setmetatable({}, ({}).mt28)
;({}).id = 10
;({}).name = "AUTO_GEN_rank_system_rank_system_name_10"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_10"
;({}).open_func_id = 1801
;({}).like_type = 10
;({}).settlement_ids = L4_4
L0_0[10] = setmetatable({}, ({}).mt11)
;({}).id = 11
;({}).name = "AUTO_GEN_rank_system_rank_system_name_11"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_11"
;({}).like_type = 11
;({}).settlement_ids = L4_4
L0_0[11] = setmetatable({}, ({}).mt11)
;({}).id = 12
;({}).name = "AUTO_GEN_rank_system_rank_system_name_12"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_12"
;({}).open_func_id = 4001
;({}).like_type = 12
;({}).hint_show_key = "cloth_rank_rule"
;({}).settlement_ids = L4_4
L0_0[12] = setmetatable({}, ({}).mt11)
;({}).id = 13
;({}).name = "AUTO_GEN_rank_system_rank_system_name_13"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_13"
;({}).like_type = 13
;({}).settlement_ids = L4_4
L0_0[13] = setmetatable({}, ({}).mt11)
;({}).id = 14
;({}).name = "AUTO_GEN_rank_system_rank_system_name_14"
;({}).like_type = 14
;({}).settlement_ids = L4_4
L0_0[14] = setmetatable({}, ({}).mt29)
;({}).id = 15
;({}).name = "AUTO_GEN_rank_system_rank_system_name_15"
;({}).like_type = 15
;({}).settlement_ids = L4_4
L0_0[15] = setmetatable({}, ({}).mt29)
;({}).id = 16
;({}).name = "AUTO_GEN_rank_system_rank_system_name_16"
;({}).like_type = 16
;({}).settlement_ids = L4_4
L0_0[16] = setmetatable({}, ({}).mt29)
;({}).id = 17
;({}).name = "AUTO_GEN_rank_system_rank_system_name_17"
;({}).like_type = 17
;({}).settlement_ids = L4_4
L0_0[17] = setmetatable({}, ({}).mt29)
;({}).id = 18
;({}).name = "AUTO_GEN_rank_system_rank_system_name_18"
;({}).like_type = 18
;({}).settlement_ids = L4_4
L0_0[18] = setmetatable({}, ({}).mt29)
;({}).id = 19
;({}).name = "AUTO_GEN_rank_system_rank_system_name_19"
;({}).like_type = 19
;({}).settlement_ids = L4_4
L0_0[19] = setmetatable({}, ({}).mt29)
;({}).id = 20
;({}).name = "AUTO_GEN_rank_system_rank_system_name_20"
;({}).like_type = 20
;({}).settlement_ids = L4_4
L0_0[20] = setmetatable({}, ({}).mt29)
;({}).id = 21
;({}).name = "AUTO_GEN_rank_system_rank_system_name_21"
;({}).like_type = 21
;({}).settlement_ids = L4_4
L0_0[21] = setmetatable({}, ({}).mt29)
;({}).id = 22
;({}).name = "AUTO_GEN_rank_system_rank_system_name_22"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_22"
;({}).refresh_type = 1
;({}).rank_limit = 50
;({}).cache_rank = 100
;({}).open_func_id = 6
;({}).settlement_ids = L4_4
L0_0[22] = setmetatable({}, ({}).mt3)
;({}).id = 23
;({}).name = "AUTO_GEN_rank_system_rank_system_name_23"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_8"
;({}).refresh_type = 0
;({}).rank_limit = 30
;({}).cache_rank = 9999
;({}).settlement_ids = L4_4
L0_0[23] = setmetatable({}, ({}).mt3)
;({}).id = 24
;({}).name = "AUTO_GEN_rank_system_rank_system_name_24"
;({}).settlement_ids = L4_4
L0_0[24] = setmetatable({}, ({}).mt25)
;({}).id = 25
;({}).name = "AUTO_GEN_rank_system_rank_system_name_25"
;({}).settlement_ids = L4_4
L0_0[25] = setmetatable({}, ({}).mt25)
;({}).id = 26
;({}).name = "AUTO_GEN_rank_system_rank_system_name_26"
;({}).settlement_ids = L4_4
L0_0[26] = setmetatable({}, ({}).mt25)
;({}).id = 27
;({}).name = "AUTO_GEN_rank_system_rank_system_name_27"
;({}).settlement_ids = L4_4
L0_0[27] = setmetatable({}, ({}).mt25)
;({}).id = 28
;({}).name = "AUTO_GEN_rank_system_rank_system_name_28"
;({}).settlement_ids = L4_4
L0_0[28] = setmetatable({}, ({}).mt25)
;({}).id = 30
;({}).name = "AUTO_GEN_rank_system_rank_system_name_30"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_5"
;({}).open_func_id = 136
;({}).like_type = 145
;({}).settlement_ids, ({})[1] = {}, 312
L0_0[30] = setmetatable({}, ({}).mt11)
;({}).id = 31
;({}).name = "AUTO_GEN_rank_system_rank_system_name_31"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_31"
;({}).open_func_id = 9
;({}).like_type = 31
;({}).settlement_ids, ({})[1] = {}, 311
L0_0[31] = setmetatable({}, ({}).mt11)
;({}).id = 32
;({}).name = "AUTO_GEN_rank_system_rank_system_name_32"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_32"
;({}).open_func_id = 6901
;({}).like_type = 32
;({}).settlement_ids, ({})[1] = {}, 321
L0_0[32] = setmetatable({}, ({}).mt11)
;({}).id = 33
;({}).name = "AUTO_GEN_rank_system_rank_system_name_33"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_33"
;({}).open_func_id = 7601
;({}).like_type = 33
;({}).settlement_ids = L4_4
L0_0[33] = setmetatable({}, ({}).mt11)
;({}).id = 34
;({}).name = "AUTO_GEN_rank_system_rank_system_name_34"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_8"
;({}).open_func_id = 7301
;({}).like_type = 34
;({}).settlement_ids = L4_4
L0_0[34] = setmetatable({}, ({}).mt11)
;({}).id = 35
;({}).name = "AUTO_GEN_rank_system_rank_system_name_35"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_35"
;({}).like_type = 35
;({}).settlement_ids = L4_4
L0_0[35] = setmetatable({}, ({}).mt11)
;({}).id = 36
;({}).name = "AUTO_GEN_rank_system_rank_system_name_36"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_36"
;({}).like_type = 36
;({}).settlement_ids = L4_4
L0_0[36] = setmetatable({}, ({}).mt11)
;({}).id = 37
;({}).name = "AUTO_GEN_rank_system_rank_system_name_37"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_37"
;({}).like_type = 37
;({}).settlement_ids = L4_4
L0_0[37] = setmetatable({}, ({}).mt11)
;({}).id = 38
;({}).name = "AUTO_GEN_rank_system_rank_system_name_38"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_38"
;({}).like_type = 38
;({}).settlement_ids = L4_4
L0_0[38] = setmetatable({}, ({}).mt11)
;({}).id = 39
;({}).name = "AUTO_GEN_rank_system_rank_system_name_39"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_39"
;({}).like_type = 39
;({}).settlement_ids = L4_4
L0_0[39] = setmetatable({}, ({}).mt11)
;({}).id = 40
;({}).name = "AUTO_GEN_rank_system_rank_system_name_40"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_40"
;({}).like_type = 40
;({}).settlement_ids = L4_4
L0_0[40] = setmetatable({}, ({}).mt11)
;({}).id = 41
;({}).name = "AUTO_GEN_rank_system_rank_system_name_41"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_41"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_41"
;({}).refresh_type = 0
;({}).rank_limit = 300
;({}).cache_rank = 600
;({}).open_func_id = 1801
;({}).like_type = 41
;({}).settlement_ids = L4_4
L0_0[41], ({}).obj_type = {}, 3
;({}).id = 42
;({}).name = "AUTO_GEN_rank_system_rank_system_name_42"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_42"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_42"
;({}).refresh_type = 0
;({}).rank_limit = 300
;({}).cache_rank = 600
;({}).open_func_id = 7801
;({}).like_type = 42
;({}).settlement_ids = L4_4
L0_0[42], ({}).obj_type = {}, 1
;({}).id = 43
;({}).name = "AUTO_GEN_rank_system_rank_system_name_43"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_43"
;({}).like_type = 43
;({}).settlement_ids = L4_4
L0_0[43] = setmetatable({}, ({}).mt11)
;({}).id = 44
;({}).name = "AUTO_GEN_rank_system_rank_system_name_44"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_44"
;({}).like_type = 6
;({}).settlement_ids = L4_4
L0_0[44] = setmetatable({}, ({}).mt11)
;({}).id = 45
;({}).name = "AUTO_GEN_rank_system_rank_system_name_45"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_45"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).rank_limit = 300
;({}).cache_rank = 500
;({}).like_type = 45
;({}).settlement_ids = L4_4
L0_0[45], ({}).obj_type = {}, 1
;({}).id = 104
;({}).name = "AUTO_GEN_rank_system_rank_system_name_104"
;({}).like_type = 104
;({}).settlement_ids, ({})[1] = {}, 1041
L0_0[104] = setmetatable({}, ({}).mt30)
;({}).id = 114
;({}).name = "AUTO_GEN_rank_system_rank_system_name_30"
;({}).like_type = 114
;({}).settlement_ids, ({})[1] = {}, 1141
L0_0[114] = setmetatable({}, ({}).mt30)
;({}).id = 124
;({}).name = "AUTO_GEN_rank_system_rank_system_name_124"
;({}).like_type = 124
;({}).settlement_ids, ({})[1] = {}, 1241
L0_0[124] = setmetatable({}, ({}).mt30)
;({}).id = 134
;({}).name = "AUTO_GEN_rank_system_rank_system_name_134"
;({}).like_type = 134
;({}).settlement_ids, ({})[1] = {}, 1341
L0_0[134] = setmetatable({}, ({}).mt30)
;({}).id = 144
;({}).name = "AUTO_GEN_rank_system_rank_system_name_144"
;({}).like_type = 144
;({}).settlement_ids, ({})[1] = {}, 1441
L0_0[144] = setmetatable({}, ({}).mt30)
;({}).id = 151
;({}).name = "AUTO_GEN_rank_system_rank_system_name_151"
;({}).like_type = 151
;({}).settlement_ids = L4_4
L0_0[151] = setmetatable({}, ({}).mt31)
;({}).id = 152
;({}).name = "AUTO_GEN_rank_system_rank_system_name_152"
;({}).like_type = 152
;({}).settlement_ids = L4_4
L0_0[152] = setmetatable({}, ({}).mt31)
;({}).id = 153
;({}).name = "AUTO_GEN_rank_system_rank_system_name_153"
;({}).like_type = 153
;({}).settlement_ids = L4_4
L0_0[153] = setmetatable({}, ({}).mt31)
;({}).id = 154
;({}).name = "AUTO_GEN_rank_system_rank_system_name_154"
;({}).like_type = 154
;({}).settlement_ids = L4_4
L0_0[154] = setmetatable({}, ({}).mt31)
;({}).id = 301
;({}).name = "AUTO_GEN_rank_system_rank_system_name_301"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_7"
;({}).like_type = 301
;({}).settlement_ids, ({})[1] = {}, 3011
L0_0[301] = setmetatable({}, ({}).mt12)
;({}).id = 302
;({}).name = "AUTO_GEN_rank_system_rank_system_name_302"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_302"
;({}).like_type = 302
;({}).settlement_ids, ({})[1] = {}, 3021
L0_0[302] = setmetatable({}, ({}).mt12)
;({}).id = 303
;({}).name = "AUTO_GEN_rank_system_rank_system_name_303"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_10"
;({}).like_type = 303
;({}).settlement_ids, ({})[1] = {}, 3031
L0_0[303] = setmetatable({}, ({}).mt12)
;({}).id = 304
;({}).name = "AUTO_GEN_rank_system_rank_system_name_304"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_14"
;({}).like_type = 304
;({}).settlement_ids, ({})[1] = {}, 3041
L0_0[304] = setmetatable({}, ({}).mt12)
;({}).id = 305
;({}).name = "AUTO_GEN_rank_system_rank_system_name_8"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_8"
;({}).like_type = 305
;({}).settlement_ids, ({})[1] = {}, 3051
L0_0[305] = setmetatable({}, ({}).mt12)
;({}).id = 306
;({}).name = "AUTO_GEN_rank_system_rank_system_name_306"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_306"
;({}).like_type = 306
;({}).settlement_ids, ({})[1] = {}, 3061
L0_0[306] = setmetatable({}, ({}).mt12)
;({}).id = 307
;({}).name = "AUTO_GEN_rank_system_rank_system_name_307"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_307"
;({}).like_type = 307
;({}).settlement_ids, ({})[1] = {}, 3071
L0_0[307] = setmetatable({}, ({}).mt16)
;({}).id = 308
;({}).name = "AUTO_GEN_rank_system_rank_system_name_308"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_308"
;({}).like_type = 308
;({}).settlement_ids, ({})[1] = {}, 3081
L0_0[308] = setmetatable({}, ({}).mt16)
;({}).id = 309
;({}).name = "AUTO_GEN_rank_system_rank_system_name_309"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_309"
;({}).like_type = 309
;({}).settlement_ids, ({})[1] = {}, 3091
L0_0[309] = setmetatable({}, ({}).mt16)
local L5_5 = L5_5
;({}).id = 310
;({}).name = "AUTO_GEN_rank_system_rank_system_name_310"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_310"
;({}).like_type = 310
;({}).settlement_ids, ({})[1] = {}, 3101
L0_0[310] = setmetatable({}, ({}).mt16)
;({}).id = 311
;({}).name = "AUTO_GEN_rank_system_rank_system_name_311"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_311"
;({}).cache_rank = 9999
;({}).like_type = 0
;({}).settlement_ids = L4_4
L0_0[311] = L5_5({}, ({}).mt17)
;({}).id = 312
;({}).name = "AUTO_GEN_rank_system_rank_system_name_312"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_312"
;({}).like_type = 312
;({}).settlement_ids, ({})[1] = {}, 3121
L0_0[312] = L5_5({}, ({}).mt12)
;({}).id = 313
;({}).name = "AUTO_GEN_rank_system_rank_system_name_313"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_313"
;({}).like_type = 313
;({}).settlement_ids, ({})[1] = {}, 3131
L0_0[313] = L5_5({}, ({}).mt12)
;({}).id = 314
;({}).name = "AUTO_GEN_rank_system_rank_system_name_314"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_314"
;({}).like_type = 314
;({}).settlement_ids, ({})[1] = {}, 3141
L0_0[314] = L5_5({}, ({}).mt12)
;({}).id = 315
;({}).name = "AUTO_GEN_rank_system_rank_system_name_315"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_315"
;({}).like_type = 315
;({}).settlement_ids, ({})[1] = {}, 3151
L0_0[315] = L5_5({}, ({}).mt12)
;({}).id = 316
;({}).name = "AUTO_GEN_rank_system_rank_system_name_316"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_316"
;({}).like_type = 316
;({}).settlement_ids, ({})[1] = {}, 3161
L0_0[316] = L5_5({}, ({}).mt12)
;({}).id = 317
;({}).name = "AUTO_GEN_rank_system_rank_system_name_317"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_317"
;({}).rank_limit = 100
;({}).cache_rank = 9999
;({}).open_func_id = 302
;({}).like_type = 317
;({}).settlement_ids, ({})[1] = {}, 3171
L0_0[317] = L5_5({}, ({}).mt6)
;({}).id = 318
;({}).name = "AUTO_GEN_rank_system_rank_system_name_318"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_6"
;({}).rank_limit = 300
;({}).cache_rank = 600
;({}).open_func_id = 7
;({}).like_type = 6
;({}).settlement_ids, ({})[1] = {}, 6
L0_0[318] = L5_5({}, ({}).mt6)
;({}).id = 401
;({}).name = "AUTO_GEN_rank_system_rank_system_name_401"
;({}).settlement_ids, ({})[1] = {}, 4011
L0_0[401] = L5_5({}, ({}).mt8)
;({}).id = 402
;({}).name = "AUTO_GEN_rank_system_rank_system_name_402"
;({}).settlement_ids = L4_4
L0_0[402] = L5_5({}, ({}).mt8)
;({}).id = 500
;({}).name = "AUTO_GEN_rank_system_rank_system_name_500"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_500"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 60
;({}).cache_rank = 60
;({}).like_type = 0
;({}).settlement_ids, ({})[1] = {}, 5001
;({}).obj_type = 1
L0_0[500], ({}).take_snapshot_before_rank = {}, 10
;({}).id = 501
;({}).name = "AUTO_GEN_rank_system_rank_system_name_501"
;({}).settlement_ids, ({})[1] = {}, 5011
L0_0[501] = L5_5({}, ({}).mt27)
;({}).id = 502
;({}).name = "AUTO_GEN_rank_system_rank_system_name_502"
;({}).settlement_ids, ({})[1] = {}, 5021
L0_0[502] = L5_5({}, ({}).mt27)
;({}).id = 503
;({}).name = "AUTO_GEN_rank_system_rank_system_name_503"
;({}).settlement_ids, ({})[1] = {}, 5031
L0_0[503] = L5_5({}, ({}).mt27)
;({}).id = 504
;({}).name = "AUTO_GEN_rank_system_rank_system_name_504"
;({}).settlement_ids, ({})[1] = {}, 5041
L0_0[504] = L5_5({}, ({}).mt27)
;({}).id = 505
;({}).name = "AUTO_GEN_rank_system_rank_system_name_505"
;({}).settlement_ids, ({})[1] = {}, 5051
L0_0[505] = L5_5({}, ({}).mt27)
;({}).id = 506
;({}).name = "AUTO_GEN_rank_system_rank_system_name_506"
;({}).settlement_ids, ({})[1] = {}, 5061
L0_0[506] = L5_5({}, ({}).mt27)
;({}).id = 507
;({}).name = "AUTO_GEN_rank_system_rank_system_name_507"
;({}).settlement_ids, ({})[1] = {}, 5071
L0_0[507] = L5_5({}, ({}).mt27)
;({}).id = 508
;({}).name = "AUTO_GEN_rank_system_rank_system_name_508"
;({}).settlement_ids, ({})[1] = {}, 5081
L0_0[508] = L5_5({}, ({}).mt27)
;({}).id = 601
;({}).name = "AUTO_GEN_rank_system_rank_system_name_601"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_601"
;({}).rank_limit = 300
;({}).cache_rank = 2000
;({}).open_func_id = 7703
;({}).like_type = 501
;({}).settlement_ids, ({})[1] = {}, 6011
L0_0[601] = L5_5({}, ({}).mt6)
;({}).id = 701
;({}).name = "AUTO_GEN_rank_system_rank_system_name_701"
;({}).rank_limit = 9999
;({}).cache_rank = 9999
;({}).open_func_id = 7701
;({}).like_type = 502
;({}).settlement_ids, ({})[1] = {}, 7011
L0_0[701] = L5_5({}, ({}).mt6)
;({}).id = 702
;({}).name = "AUTO_GEN_rank_system_rank_system_name_701"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_22"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 100
;({}).open_func_id = 7701
;({}).like_type = 503
;({}).settlement_ids, ({})[1] = {}, 7021
L0_0[702], ({}).obj_type = {}, 2
;({}).id = 801
;({}).name = "AUTO_GEN_rank_system_rank_system_name_801"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_601"
;({}).rank_limit = 1000
;({}).cache_rank = 9999
;({}).open_func_id = 9001
;({}).like_type = 1003
;({}).settlement_ids, ({})[1] = {}, 8011
;({}).settlement_ids, ({})[2] = {}, 8012
L0_0[801] = L5_5({}, ({}).mt6)
;({}).id = 901
;({}).name = "AUTO_GEN_rank_system_rank_system_name_901"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_901"
;({}).rank_limit = 100
;({}).cache_rank = 500
;({}).open_func_id = 9201
;({}).like_type = 0
;({}).settlement_ids, ({})[1] = {}, 9011
L0_0[901] = L5_5({}, ({}).mt6)
;({}).id = 1001
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1001"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1001"
;({}).settlement_ids = L4_4
L0_0[1001] = L5_5({}, ({}).mt9)
;({}).id = 1002
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1002"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1002"
;({}).settlement_ids, ({})[1] = {}, 10021
L0_0[1002] = L5_5({}, ({}).mt9)
;({}).id = 1003
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1003"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1002"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 3
;({}).rank_limit = 9999
;({}).cache_rank = 9999
;({}).like_type = 0
;({}).settlement_ids, ({})[1] = {}, 10031
L0_0[1003], ({}).obj_type = {}, 1
;({}).id = 1004
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1004"
;({}).rank_limit = 30
;({}).cache_rank = 50
;({}).settlement_ids, ({})[1] = {}, 10041
;({}).obj_type = 2
L0_0[1004] = L5_5({}, ({}).mt19)
;({}).id = 1005
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1005"
;({}).rank_limit = 9999
;({}).cache_rank = 9999
;({}).settlement_ids, ({})[1] = {}, 10051
;({}).obj_type = 1
L0_0[1005] = L5_5({}, ({}).mt19)
;({}).id = 1101
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1101"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_14"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 100
;({}).like_type = 10002
;({}).settlement_ids, ({})[1] = {}, 11011
;({}).obj_type = 1
;({}).scope_group_type = 1
;({}).if_show = 1
L0_0[1101], ({}).if_reward = {}, 1
;({}).id = 1102
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1102"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 500
;({}).cache_rank = 500
;({}).settlement_ids = L4_4
;({}).obj_type = 1
;({}).scope_group_type = 1
;({}).if_show = 0
L0_0[1102], ({}).if_reward = {}, 0
;({}).id = 1103
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1103"
;({}).settlement_ids = L4_4
L0_0[1103] = L5_5({}, ({}).mt14)
;({}).id = 1104
;({}).name = "AUTO_GEN_rank_system_rank_system_name_11"
;({}).settlement_ids = L4_4
L0_0[1104] = L5_5({}, ({}).mt14)
;({}).id = 1105
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1105"
;({}).settlement_ids = L4_4
L0_0[1105] = L5_5({}, ({}).mt14)
;({}).id = 1106
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1106"
;({}).settlement_ids = L4_4
L0_0[1106] = L5_5({}, ({}).mt14)
;({}).id = 1107
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1107"
;({}).settlement_ids = L4_4
L0_0[1107] = L5_5({}, ({}).mt14)
;({}).id = 1108
;({}).settlement_ids, ({})[1] = {}, 11081
L0_0[1108] = L5_5({}, ({}).mt1)
;({}).id = 1109
;({}).settlement_ids = L4_4
L0_0[1109] = L5_5({}, ({}).mt1)
;({}).id = 1110
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1110"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1110"
;({}).settlement_ids, ({})[1] = {}, 11101
L0_0[1110] = L5_5({}, ({}).mt15)
;({}).id = 1111
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1111"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1111"
;({}).settlement_ids, ({})[1] = {}, 11111
L0_0[1111] = L5_5({}, ({}).mt15)
;({}).id = 1112
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1112"
;({}).settlement_ids = L4_4
L0_0[1112] = L5_5({}, ({}).mt15)
;({}).id = 1113
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1113"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1113"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).settlement_ids, ({})[1] = {}, 11131
L0_0[1113] = L5_5({}, ({}).mt2)
;({}).id = 1114
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1114"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1114"
;({}).refresh_type = 2
;({}).rank_limit = 50
;({}).settlement_ids, ({})[1] = {}, 11141
L0_0[1114] = L5_5({}, ({}).mt2)
;({}).id = 1115
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1115"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1115"
;({}).rank_limit = 100
;({}).cache_rank = 100
;({}).settlement_ids = L4_4
L0_0[1115] = L5_5({}, ({}).mt7)
;({}).id = 1116
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1116"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_45"
;({}).rank_limit = 50
;({}).cache_rank = 9999
;({}).settlement_ids, ({})[1] = {}, 11161
L0_0[1116] = L5_5({}, ({}).mt7)
;({}).id = 1117
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1117"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).rank_limit = 300
;({}).settlement_ids, ({})[1] = {}, 11171
;({}).obj_type = 1
;({}).scope_group_type = 1
L0_0[1117] = L5_5({}, ({}).mt18)
;({}).id = 1118
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1118"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_22"
;({}).rank_limit = 50
;({}).settlement_ids, ({})[1] = {}, 11181
;({}).obj_type = 2
L0_0[1118] = L5_5({}, ({}).mt18)
;({}).id = 1119
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1119"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1002"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_22"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 100
;({}).hint_show_key = "alliance_merge_rank"
;({}).settlement_ids, ({})[1] = {}, 11191
;({}).obj_type = 2
;({}).if_show = 0
L0_0[1119], ({}).if_reward = {}, 0
;({}).id = 1120
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1120"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1120"
;({}).rank_limit = 100
;({}).settlement_ids = L4_4
L0_0[1120] = L5_5({}, ({}).mt4)
;({}).id = 1122
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1122"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1110"
;({}).rank_limit = 300
;({}).settlement_ids, ({})[1] = {}, 11221
;({}).scope_group_type = 1
;({}).if_show = 0
;({}).if_reward = 0
L0_0[1122] = L5_5({}, ({}).mt4)
;({}).id = 1130
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1130"
;({}).settlement_ids, ({})[1] = {}, 18001
L0_0[1130] = L5_5({}, ({}).mt20)
;({}).id = 1131
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1131"
;({}).settlement_ids, ({})[1] = {}, 18002
L0_0[1131] = L5_5({}, ({}).mt20)
;({}).id = 1132
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1132"
;({}).settlement_ids, ({})[1] = {}, 18003
L0_0[1132] = L5_5({}, ({}).mt24)
;({}).id = 1133
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1133"
;({}).settlement_ids, ({})[1] = {}, 18004
L0_0[1133] = L5_5({}, ({}).mt24)
;({}).id = 1134
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1134"
;({}).settlement_ids, ({})[1] = {}, 18005
L0_0[1134] = L5_5({}, ({}).mt21)
;({}).id = 1135
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1135"
;({}).settlement_ids, ({})[1] = {}, 18006
L0_0[1135] = L5_5({}, ({}).mt21)
;({}).id = 1136
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1001"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1136"
;({}).cache_rank = 300
;({}).settlement_ids = L4_4
;({}).scope_group_type = 1
L0_0[1136] = L5_5({}, ({}).mt17)
;({}).id = 1140
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1140"
;({}).settlement_ids, ({})[1] = {}, 19001
L0_0[1140] = L5_5({}, ({}).mt22)
;({}).id = 1141
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1141"
;({}).settlement_ids, ({})[1] = {}, 19002
L0_0[1141] = L5_5({}, ({}).mt22)
;({}).id = 1142
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1142"
;({}).settlement_ids, ({})[1] = {}, 19003
L0_0[1142] = L5_5({}, ({}).mt23)
;({}).id = 1143
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1143"
;({}).settlement_ids, ({})[1] = {}, 19004
L0_0[1143] = L5_5({}, ({}).mt23)
;({}).id = 1144
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1144"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1144"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_22"
;({}).refresh_type = 0
;({}).rank_limit = 100
;({}).cache_rank = 200
;({}).hint_show_key = "galactic_cycle_rank_guild_rule"
;({}).settlement_ids, ({})[1] = {}, 19005
L0_0[1144], ({}).obj_type = {}, 2
;({}).id = 1201
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1201"
;({}).settlement_ids, ({})[1] = {}, 12011
;({}).settlement_ids, ({})[2] = {}, 12111
;({}).scope_group_type = 2
L0_0[1201] = L5_5({}, ({}).mt13)
;({}).id = 1203
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1203"
;({}).settlement_ids, ({})[1] = {}, 12031
;({}).settlement_ids, ({})[2] = {}, 12131
;({}).scope_group_type = 3
L0_0[1203] = L5_5({}, ({}).mt13)
;({}).id = 1205
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1205"
;({}).settlement_ids, ({})[1] = {}, 12051
local ({}).settlement_ids, ({})[2], L10_10 = {}, 12151, L10_10
;({}).scope_group_type = 4
L0_0[1205] = L5_5({}, L10_10.mt13)
;({}).id = 1302
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1302"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1302"
;({}).rank_limit = 1000
;({}).cache_rank = 2000
;({}).like_type = 10002
;({}).settlement_ids, ({})[1] = {}, 13020
;({}).if_show = 1
;({}).if_reward = 1
;({}).take_snapshot_before_rank = 10
L0_0[1302] = L5_5({}, L10_10.mt6)
;({}).id = 1401
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1401"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_45"
;({}).rank_limit = 9999
;({}).settlement_ids = L4_4
;({}).scope_group_type = 5
L0_0[1401] = L5_5({}, L10_10.mt5)
;({}).id = 1501
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1501"
;({}).rank_limit = 2000
;({}).settlement_ids = L4_4
L0_0[1501] = L5_5({}, L10_10.mt5)
;({}).id = 1601
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1601"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_45"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_1601"
;({}).refresh_type = 0
;({}).rank_limit = 64
;({}).cache_rank = 200
;({}).settlement_ids = L4_4
;({}).obj_type = 4
L0_0[1601], ({}).if_show = {}, 1
;({}).id = 1701
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1701"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_1701"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_4"
;({}).refresh_type = 0
;({}).rank_limit = 500
;({}).cache_rank = 9999
;({}).like_type = 12
;({}).settlement_ids = L4_4
;({}).obj_type = 1
L0_0[1701], ({}).if_show = {}, 1
;({}).id = 1702
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1702"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_1702"
;({}).settlement_ids, ({})[1] = {}, 17002
L0_0[1702] = L5_5({}, L10_10.mt10)
;({}).id = 1703
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1703"
;({}).title = "AUTO_GEN_rank_system_rank_system_name_1703"
;({}).settlement_ids, ({})[1] = {}, 17003
L0_0[1703] = L5_5({}, L10_10.mt10)
;({}).id = 1602
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1602"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_45"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_1601"
;({}).refresh_type = 0
;({}).rank_limit = 64
;({}).cache_rank = 200
;({}).settlement_ids = L4_4
;({}).obj_type = 4
L0_0[1602], ({}).if_show = {}, 1
;({}).id = 1801
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1801"
;({}).settlement_ids = L4_4
L0_0[1801] = L5_5({}, L10_10.mt26)
;({}).id = 1802
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1802"
;({}).settlement_ids = L4_4
L0_0[1802] = L5_5({}, L10_10.mt26)
;({}).id = 1803
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1803"
;({}).settlement_ids = L4_4
L0_0[1803] = L5_5({}, L10_10.mt26)
;({}).id = 1804
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1804"
;({}).settlement_ids = L4_4
local L7_7 = L7_7
L0_0[L7_7] = L5_5({}, L10_10.mt26)
L7_7 = 1805
;({}).id = 1805
;({}).name = "AUTO_GEN_rank_system_rank_system_name_1805"
;({}).title = "AUTO_GEN_rank_system_rank_system_title_1805"
;({}).sub_title = "AUTO_GEN_rank_system_rank_system_sub_title_22"
;({}).refresh_type = 3
;({}).rank_limit = 30
;({}).cache_rank = 50
;({}).like_type = 0
local L8_8.settlement_ids, ({})[1], L8_8 = {}, 17004, L8_8
L8_8.obj_type = 2
L0_0[L7_7] = L8_8
return L0_0
