"""Read original little-endian Lua 5.1 chunks without guessing control flow."""
from __future__ import annotations
import json
import struct
from dataclasses import dataclass, field
from pathlib import Path

OPS = ('MOVE LOADK LOADBOOL LOADNIL GETUPVAL GETGLOBAL GETTABLE SETGLOBAL SETUPVAL SETTABLE '
       'NEWTABLE SELF ADD SUB MUL DIV MOD POW UNM NOT LEN CONCAT JMP EQ LT LE TEST TESTSET '
       'CALL TAILCALL RETURN FORLOOP FORPREP TFORLOOP SETLIST CLOSE CLOSURE VARARG').split()

@dataclass
class Prototype:
    source: str | None
    first_line: int
    last_line: int
    nups: int
    params: int
    vararg: int
    stack: int
    code: list[int]
    constants: list
    children: list['Prototype']
    lines: list[int]
    names: list[str] = field(default_factory=list)

class Reader:
    def __init__(self, data: bytes):
        self.data=data; self.pos=0
        h=self.take(12)
        if h[:8]!=b'\x1bLua\x51\x00\x01\x04' or h[9:]!=b'\x04\x08\x00' or h[8] not in (4,8):
            raise ValueError('Unsupported Lua header '+h.hex())
        self.size_t=h[8]
    def take(self,n):
        result=self.data[self.pos:self.pos+n];self.pos+=n
        if len(result)!=n:raise ValueError('Truncated chunk')
        return result
    def uint(self):return struct.unpack('<I',self.take(4))[0]
    def string(self):
        n=int.from_bytes(self.take(self.size_t),'little')
        return self.take(n)[:-1].decode('utf8','replace') if n else None
    def proto(self):
        source=self.string();first,last=self.uint(),self.uint()
        nups,params,vararg,stack=self.take(4)
        code=[self.uint() for _ in range(self.uint())]
        constants=[]
        for _ in range(self.uint()):
            tag=self.take(1)[0]
            if tag==0:v=None
            elif tag==1:v=bool(self.take(1)[0])
            elif tag==3:v=struct.unpack('<d',self.take(8))[0]
            elif tag==4:v=self.string()
            else:raise ValueError(f'Unknown constant {tag}')
            constants.append(v)
        children=[self.proto() for _ in range(self.uint())]
        lines=[self.uint() for _ in range(self.uint())]
        for _ in range(self.uint()):self.string();self.take(8)
        for _ in range(self.uint()):self.string()
        p=Prototype(source,first,last,nups,params,vararg,stack,code,constants,children,lines)
        for pc,word in enumerate(code):
            op,a,b,c,bx,sbx=decode(word)
            if op!='CLOSURE':continue
            child=children[bx]
            end=min(len(code),pc+child.nups+8)
            for next_word in code[pc+child.nups+1:end]:
                op2,a2,b2,c2,*_=decode(next_word)
                if op2=='SETTABLE' and c2==a and b2>=256:
                    name=constants[b2-256]
                    if isinstance(name,str):child.names.append(name)
                    break
                if op2=='CLOSURE':break
        return p

def decode(word):
    op=OPS[word&63];a=(word>>6)&255;c=(word>>14)&511;b=(word>>23)&511
    bx=word>>14
    return op,a,b,c,bx,bx-131071

def quoted(v):return json.dumps(v,ensure_ascii=False)

def disassemble(data: bytes, name: str) -> str:
    reader=Reader(data);root=reader.proto()
    if reader.pos!=len(data):raise ValueError('Trailing bytes')
    output=[f'; Original Lua 5.1 instruction listing: {name}',
            '; Generated by tools/lua51_disassemble.py; no control-flow reconstruction.', '']
    def walk(p,path):
        output.extend([f'; Function {path}: '+', '.join(p.names),
                       f'; Source lines {p.first_line}-{p.last_line}; params={p.params}; upvalues={p.nups}; stack={p.stack}'])
        def rk(x):return 'K'+str(x-256)+'('+quoted(p.constants[x-256])+')' if x>=256 else 'R'+str(x)
        for pc,word in enumerate(p.code,1):
            op,a,b,c,bx,sbx=decode(word);note='';args=''
            if op in ('LOADK','GETGLOBAL','SETGLOBAL'):
                args=f'R{a} K{bx}';note=quoted(p.constants[bx])
            elif op=='CLOSURE':args=f'R{a} F{path}.{bx+1}';note=', '.join(p.children[bx].names)
            elif op in ('JMP','FORLOOP','FORPREP'):args=f'R{a} {sbx:+d}';note=f'target PC {pc+1+sbx}'
            elif op in ('GETTABLE','SELF'):args=f'R{a} R{b} {rk(c)}'
            elif op=='SETTABLE':args=f'R{a} {rk(b)} {rk(c)}'
            elif op in ('ADD','SUB','MUL','DIV','MOD','POW','EQ','LT','LE'):args=f'{a if op in ("EQ","LT","LE") else "R"+str(a)} {rk(b)} {rk(c)}'
            elif op in ('MOVE','UNM','NOT','LEN','LOADNIL'):args=f'R{a} R{b}'
            elif op in ('GETUPVAL','SETUPVAL'):args=f'R{a} U{b}'
            else:args=f'R{a} {b} {c}'
            line=p.lines[pc-1] if len(p.lines)>=pc else '-'
            output.append(f'{pc:5d} [{line}] {op:10s} {args}'+(f' ; {note}' if note else ''))
        output.append('')
        for i,child in enumerate(p.children,1):walk(child,f'{path}.{i}')
    walk(root,'0')
    return '\n'.join(line.rstrip() for line in output).rstrip()+'\n'

if __name__=='__main__':
    import argparse
    parser=argparse.ArgumentParser();parser.add_argument('source',type=Path);parser.add_argument('output',type=Path)
    args=parser.parse_args();args.output.write_text(disassemble(args.source.read_bytes(),args.source.name),encoding='utf8')
